export const environment = {
  name: 'dev',
  title: 'angular-playground',
  production: false,
  backendDelay: 100,
  httpRetry: 0,
  loggingBackendUrl: true,
  loggingBackendRequestHeaders: false,
  loggingBackendRequest: false,
  loggingBackendResponse: false,
  apiEndpoint: '',
  messageDismissible: false,
  messageSuccessTimeout: 3000,
  messageInfoTimeout: 5000,
  messageAnotherTimeout: 1000000,
};
