export const environment = {
  name: 'prod',
  title: 'angular-playground',
  production: true,
  backendDelay: 0,
  httpRetry: 0,
  loggingBackendUrl: true,
  loggingBackendRequestHeaders: false,
  loggingBackendRequest: false,
  loggingBackendResponse: false,
  apiEndpoint: '',
  messageDismissible: false,
  messageSuccessTimeout: 5000,
  messageInfoTimeout: 10000,
  messageAnotherTimeout: 15000,
};
